[project]
name = "project-name"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "debugpy",
  "setuptools"
]

#[tool.pyright]
#include = [ "src" ]

[build-system]
requires = [ "setuptools" ]
build-backend = "setuptools.build_meta"

