[project]
name = "pypacking"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "debugpy",
  "hatchling"
]

#[tool.pyright]
#include = [ "src" ]

[build-system]
requires = [ "hatchling" ]
build-backend = "hatchling.build"

